name: 'CI - Backend ğŸ§¬'

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches:
      - 'feature/**'
      - 'fix/**'

jobs:
  ci-build-backend:
    name: 'Build ğŸ—'
    uses: ./.github/workflows/_build-backend.yml
  ci-lint-backend:
    name: 'Code Quality ğŸ’'
    needs: ci-build-backend
    uses: ./.github/workflows/_lint-backend.yml
  ci-test-backend:
    name: 'Test ğŸ”¬'
    needs: ci-build-backend
    uses: ./.github/workflows/_test-backend.yml
